/** @type {import('tailwindcss').Config} */
module.exports = {
        darkMode: "class",
        content: [
          "./src/**/*.{js,ts,jsx,tsx,mdx}",
        ],
        theme: {
          extend: {
            "colors": {
                    "on-tertiary-fixed": "#002110",
                    "on-primary-fixed-variant": "#00419e",
                    "tertiary-fixed": "#7efab3",
                    "surface-variant": "#e2e2e5",
                    "surface-bright": "#f9f9fc",
                    "on-primary-fixed": "#001946",
                    "background": "#f9f9fc",
                    "inverse-surface": "#2f3133",
                    "primary-container": "#dae2ff",
                    "on-secondary-fixed": "#301400",
                    "on-secondary": "#ffffff",
                    "tertiary-container": "#7efab3",
                    "tertiary-fixed-dim": "#61dd98",
                    "surface": "#f9f9fc",
                    "secondary-fixed-dim": "#ffb785",
                    "surface-tint": "#2559bd",
                    "on-primary-container": "#001946",
                    "secondary-fixed": "#ffdcc6",
                    "on-tertiary": "#ffffff",
                    "primary": "#0047ab",
                    "surface-container-lowest": "#ffffff",
                    "on-tertiary-container": "#003d1f",
                    "on-tertiary-fixed-variant": "#00522f",
                    "surface-container-highest": "#e2e2e5",
                    "inverse-primary": "#b1c5ff",
                    "outline": "#737784",
                    "on-secondary-fixed-variant": "#723700",
                    "on-error-container": "#93000a",
                    "tertiary": "#003f23",
                    "error-container": "#ffdad6",
                    "primary-fixed-dim": "#b1c5ff",
                    "on-background": "#1a1c1e",
                    "secondary-container": "#ffb785",
                    "on-primary": "#ffffff",
                    "secondary": "#7c3a00",
                    "on-surface": "#1a1c1e",
                    "on-surface-variant": "#434653",
                    "error": "#ba1a1a",
                    "on-error": "#ffffff",
                    "surface-container-low": "#f3f3f6",
                    "inverse-on-surface": "#f0f0f3",
                    "primary-fixed": "#dae2ff",
                    "surface-container": "#eeeef0",
                    "surface-container-high": "#e8e8ea",
                    "on-secondary-container": "#432100",
                    "outline-variant": "#c3c6d5",
                    "surface-dim": "#dadadc",
                    "impact-emerald": "#059669",
                    "validation-amber": "#b45309",
                    "expert-purple": "#7c3aed"
            },
            "borderRadius": {
                    "DEFAULT": "0.125rem",
                    "lg": "0.25rem",
                    "xl": "0.5rem",
                    "full": "0.75rem"
            },
            "spacing": {
                    "margin-mobile": "16px",
                    "stack-lg": "32px",
                    "gutter": "16px",
                    "base": "4px",
                    "stack-md": "16px",
                    "stack-sm": "8px",
                    "margin-desktop": "32px"
            },
            "fontFamily": {
                    "body-lg": ["var(--font-inter)"],
                    "headline-md": ["var(--font-hanken)"],
                    "label-xs": ["var(--font-inter)"],
                    "display-lg-mobile": ["var(--font-hanken)"],
                    "display-lg": ["var(--font-hanken)"],
                    "body-md": ["var(--font-inter)"],
                    "label-sm": ["var(--font-inter)"],
                    "metric-num": ["var(--font-hanken)"],
                    "title-md": ["var(--font-hanken)"],
                    "title-sm": ["var(--font-hanken)"],
                    "title-lg": ["var(--font-hanken)"],
                    "headline-lg": ["var(--font-hanken)"],
                    "headline-sm": ["var(--font-hanken)"],
                    "body-sm": ["var(--font-inter)"],
                    "label-md": ["var(--font-inter)"]
            },
            "fontSize": {
                    "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                    "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                    "label-xs": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
                    "display-lg-mobile": ["26px", {"lineHeight": "32px", "fontWeight": "700"}],
                    "display-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
                    "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                    "label-sm": ["14px", {"lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "500"}],
                    "title-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
                    "title-sm": ["16px", {"lineHeight": "24px", "fontWeight": "600"}],
                    "title-lg": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
                    "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
                    "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
                    "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
                    "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}]
            }
          },
        },
      };
